### ISSUE TITLE
helperCreateClassFeaturesPlugin.injectInitialization is not a function

### ISSUE THREAD

**Issue by allthesignals** [ember-modifier/ember-modifier#71] opened 2021-02-02 05:33 UTC
Hi,

After recreating a yarn.lock file, I'm seeing this: 

> $ ember serve
> Build Error (broccoli-persistent-filter:Babel > [Babel: ember-modifier]) in ember-modifier/-private/class/modifier-manager.ts
> 
> **/Users/wmattgardner/labs-zola/ember-modifier/-private/class/modifier-manager.ts**: (0 , _helperCreateClassFeaturesPlugin.injectInitialization) is not a function
> 
> 
> Stack Trace and Error Report: /var/folders/gs/x79h3r4179gbvdh2pry1lcfc0000gn/T/error.dump.6d8f45a9f40b6a10a8abdce76940f82e.log

![image](https://user-images.githubusercontent.com/5004319/106556684-0abbb580-64ee-11eb-8622-126b7a0385f3.png)

Kinda stumped here. The package.json can be found here: https://github.com/NYCPlanning/labs-zola/blob/develop/package.json

Seems as though it's trying to reach for a file and it's one directory off (see bolded line)?

**Comment by chriskrycho** [comment] 2022-03-31 02:12
I am going to go ahead and close this since it hasn't been reproduced (and seems to have been an odd build error in any case). Feel free to reopen if it's still an issue!

**Closed by chriskrycho** 2022-03-31 02:12 UTC
